title: Developing the Web
author: Richard Crawford
email: richmeistergrad@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  All about web development. Primary focus is on front end react developing. My
  journey through gaining knowledge and skills to land an awesome job in the field.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ShieldRich # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
